menu:
    首页: /
    归档: /archives/
    微博: http://weibo.com/3774381537
    github: https://github.com/785156621
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
